meta:
  environment: zookeeper-openstack

  stemcell:
    name: bosh-openstack-kvm-ubuntu
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: zookeeper_z1
    instances: 3
    networks:
      - name: default

compilation:
  cloud_properties:
    instance_type: m1.small

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: zookeeper1
    type: dynamic
    cloud_properties:
      security_groups:
      - default
